assets:
  - d7.sql.gz
steps:
  - name: Probo site setup
    plugin: Drupal
    database: d7.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    subDirectory: www
  - name: pwd
    plugin: Shell
    command: 'pwd'
  - name: Run behat tests
    plugin: Shell
    command: 'cd $SRC_DIR/www/sites/all/tests ; composer install ; bin/behat'
