assets:
  - d7.sql.gz
steps:
  - name: Probo site setup
    plugin: Drupal
    database: d7.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    subDirectory: www
  - name: Run behat tests
    plugin: Shell
    command: 'cd www/sites/all/tests; ./bin/behat'
