assets:
  - d7.sql.gz
steps:
  - name: Probo site setup2
    plugin: Drupal
    database: d7.sql.gz
    databaseGzipped: true
    databaseUpdates: true
    subDirectory: www
  - name: Test
    plugin: Shell
    command: |
      echo '<?php ' >> ~/.drush/aliases.drushrc.php ;
      echo '$aliases["self"] = ["root" => "/src/www", "uri" => "http://default"];' >> ~/.drush/aliases.drushrc.php ;
      cd ~ ;
      drush @self cc all ;
  - name: pwd
    plugin: Shell
    command: 'pwd'
  - name: Build behat deps
    plugin: Shell
    command: 'cd $SRC_DIR/www/sites/all/tests ; composer install'
  - name: Run behat tests
    plugin: Shell
    command: '$SRC_DIR/www/sites/all/tests/bin/behat --config sites/all/tests/behat.probo.yml --tags=probo'
